In [2]:
#You declare the variable without type.
a = 3
b = True
c = 'String!'
print(a,b,c)

3 True String!


In [3]:
print(5/2)
print(int(5/2))

2.5
2


In [17]:
#Loops
arr = [1,2,3,4,5]
print('show array with for in')
for x in arr:
    print(x)
print('show array with for in range')
for x in range(len(arr)):
    print(arr[x])
print('show even numbers')
for x,i in zip(arr,range(len(arr))):
    arr[i]=arr[i]/2
#     print(x)
print(arr)
        


show array with for in
1
2
3
4
5
show array with for in range
1
2
3
4
5
show even numbers
[0.5, 1.0, 1.5, 2.0, 2.5]


In [5]:
# Array Indexing:
arr = [0,1,2,3,4,5]
print(arr[0:3])

import numpy as np
import math

origMat = np.array(arr)
mat = np.copy(origMat)
print(mat)
mat[0:3] = 0
print(mat)
mat = np.copy(origMat)
mat[(mat%2==0)] = -1
print(mat)

[0, 1, 2]
[0 1 2 3 4 5]
[0 0 0 3 4 5]
[-1  1 -1  3 -1  5]


In [14]:
import math

mat1 = np.array([
                   [1,2,3,4,5],
                   [6,7,8,9,10],
                   [11,12,13,14,15]
                   ])

mat = np.array([
                   [0.1,0.2,0.3,0.4,0.5],
                   [0.6,0.7,0.3,0.4,0.5],
                   [0.8,0.2,0.3,0.4,0.5]
                   ])
# print(mat1)
mat=mat.astype(np.uint8)
# print(mat)
# mat[1:3,1:3] = 0
# mat1=1.5*mat1+50
# mat=mat.astype('uint8')
# mat[:,:]=mat[:,:]*255
# mat[0,0]=math.floor(mat[0,0])
print(mat1.max())
# print(len(mat1))

15


In [ ]:
arrZeros = np.zeros((6,5))
arrOnes =np.ones((6,5))
print(arrZeros)
print(arrOnes)
print(arrOnes.shape)
print(arrOnes.shape[0])

In [ ]:
# Shows the fact that Python uses KEYWORD ARGUMENTS as well as the traditional positional arguments.
## Notice that: in the output of the first and second call to function fun are the same.
## In the second call (using keywords arguments), sorting arguments is not needed.


def fun(x,y,z):
    print (x,y,z)
    
fun(1,2,3);
fun(z=3,y=2,x=1)

In [ ]:
#instead of NULL: None

x = None
if (x==None):
    print('x is None')
